#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Turn a Linux console font into a C table for the framebuffer console.
#
# The output is committed rather than generated during the build, because the
# input is a file that happens to be installed on one developer's machine and not
# a dependency the build may assume. Running this again is only necessary to
# change fonts.
#
# Only PSF version 1 is read, which is what the console-setup fonts in
# /usr/share/consolefonts are: a four byte header, then one glyph per character
# as `height` bytes of eight pixels each, most significant bit leftmost. That
# layout is already what the renderer wants, so the bytes are copied through
# unchanged.
#
# Only printable ASCII is emitted. The font holds 256 glyphs in Latin-1 order,
# but the console has no way to receive anything above 0x7e: Ruby writes UTF-8
# and the renderer does not decode it.
#
# Usage:
#   ruby tools/generate-font.rb /usr/share/consolefonts/Lat15-Terminus16.psf.gz \
#     > src/console/font_8x16.c

require 'zlib'

PSF1_MAGIC = [0x36, 0x04].freeze
PSF1_MODE_512 = 0x01

FIRST = 0x20
LAST  = 0x7e

path = ARGV.shift or abort "usage: #{$PROGRAM_NAME} FONT.psf[.gz]"

data = if path.end_with?('.gz')
         Zlib::GzipReader.open(path, &:read)
       else
         File.binread(path)
       end
data = data.b

magic = data[0, 2].bytes
abort "not a PSF1 font: magic #{magic.inspect}" unless magic == PSF1_MAGIC

mode = data.getbyte(2)
height = data.getbyte(3)
count = (mode & PSF1_MODE_512).zero? ? 256 : 512
glyphs = data[4, count * height]

abort "font is #{height} rows, expected 16" unless height == 16
abort "truncated font" unless glyphs && glyphs.bytesize == count * height
abort "font has only #{count} glyphs" unless count > LAST

puts <<~HEADER
  /*
   * Generated by tools/generate-font.rb -- do not edit.
   *
   * Source: #{File.basename(path)}
   *
   * Debian states that all console fonts are public domain by nature
   * (/usr/share/doc/console-setup/copyright).
   *
   * One glyph per printable ASCII character, #{height} rows of eight pixels, most
   * significant bit leftmost.
   */

  #include "console.h"

  const uint8_t console_font[CONSOLE_FONT_GLYPHS][CONSOLE_FONT_HEIGHT] = {
HEADER

(FIRST..LAST).each do |code|
  rows = glyphs[code * height, height].bytes
  bytes = rows.map { |b| format('0x%02x', b) }.join(', ')
  label = code == 0x27 || code == 0x5c ? "'\\#{code.chr}'" : "'#{code.chr}'"
  puts format('    { %s }, /* %-5s */', bytes, label)
end

puts '};'
