#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Turn the Misaki BDF font into a C table for the framebuffer console.
#
# Misaki is an 8x8 Japanese bitmap font: half width characters occupy 4x8 and
# full width ones 8x8. Those two sizes are exactly half the console's cell in
# each direction, so a glyph drawn at twice the console's scale fills either one
# cell or two with no padding and no distortion -- which is why this font suits a
# terminal that already renders ASCII from an 8x16 one.
#
#   https://littlelimit.net/misaki.htm
#   "These fonts are free softwares. Unlimited permission is granted to use,
#    copy, and distribute it, with or without modification, either commercially
#    and noncommercially."
#
# ASCII is deliberately left out. The console draws 0x20 to 0x7e from Terminus,
# which is a designed 8x16 face rather than a 4x8 one doubled, and a Ruby prompt
# is mostly ASCII.
#
# Cell placement follows the font's own metrics. BDF stores each glyph trimmed to
# its ink, with BBX giving the size and the offset from the baseline, so the rows
# have to be placed back into an 8 row box: FONT_ASCENT is 6, so a glyph of
# `height` rows sitting at `yoff` starts at row 6 - (height + yoff).
#
# Width comes from DWIDTH rather than from a Unicode table. The font states, per
# glyph, how far the cursor advances, and that is the same distinction East Asian
# Width makes -- with the advantage that it cannot disagree with the glyph that
# is actually drawn.
#
# Usage:
#   ruby tools/generate-misaki.rb misaki_gothic.bdf > src/console/font_misaki.c

FONT_HEIGHT = 8
FONT_ASCENT = 6
FULL_WIDTH_ADVANCE = 8

path = ARGV.shift or abort "usage: #{$PROGRAM_NAME} FONT.bdf"

glyphs = {}

encoding = nil
bbx = nil
dwidth = nil
bitmap = nil
in_bitmap = false

File.foreach(path) do |line|
  line = line.strip

  case line
  when /\AENCODING\s+(-?\d+)\z/
    encoding = Regexp.last_match(1).to_i
  when /\ADWIDTH\s+(-?\d+)\s+(-?\d+)\z/
    dwidth = Regexp.last_match(1).to_i
  when /\ABBX\s+(\d+)\s+(\d+)\s+(-?\d+)\s+(-?\d+)\z/
    bbx = Regexp.last_match.captures.map(&:to_i)
  when 'BITMAP'
    bitmap = []
    in_bitmap = true
  when 'ENDCHAR'
    # Above ASCII, within the BMP, and actually drawn.
    if encoding && encoding > 0x7f && encoding <= 0xffff && bbx && bitmap
      width, height, xoff, yoff = bbx
      top = FONT_ASCENT - (height + yoff)
      rows = Array.new(FONT_HEIGHT, 0)

      bitmap.each_with_index do |hex, source_y|
        next if source_y >= height

        target_y = top + source_y
        next if target_y.negative? || target_y >= FONT_HEIGHT

        bits = hex.to_i(16)
        width.times do |source_x|
          target_x = xoff + source_x
          next if target_x.negative? || target_x >= 8
          # BDF pads each row to whole bytes from the left.
          next if (bits & (1 << (7 - source_x))).zero?

          rows[target_y] |= 1 << (7 - target_x)
        end
      end

      glyphs[encoding] = [dwidth == FULL_WIDTH_ADVANCE ? 1 : 0, rows]
    end

    encoding = nil
    bbx = nil
    dwidth = nil
    bitmap = nil
    in_bitmap = false
  else
    bitmap << line if in_bitmap && !line.empty?
  end
end

abort 'no glyphs found' if glyphs.empty?

puts <<~HEADER
  /*
   * Generated by tools/generate-misaki.rb -- do not edit.
   *
   * Misaki Gothic, Copyright (C) 2002-2021 Num Kadoma, https://littlelimit.net/
   * Unlimited permission is granted to use, copy, and distribute it, with or
   * without modification, either commercially and noncommercially, without
   * warranty.
   *
   * Sorted by code point so that lookup can bisect. Eight rows of eight pixels,
   * most significant bit leftmost; a half width glyph uses only the top four
   * bits of each row.
   */

  #include "console.h"

  const console_glyph_t console_misaki[] = {
HEADER

glyphs.keys.sort.each do |codepoint|
  wide, rows = glyphs[codepoint]
  bytes = rows.map { |b| format('0x%02x', b) }.join(', ')
  puts format('    { 0x%04x, %d, { %s } },', codepoint, wide, bytes)
end

puts '};'
puts
puts "const size_t console_misaki_count = #{glyphs.size};"

warn "#{glyphs.size} glyphs, #{glyphs.count { |_, (w, _)| w == 1 }} full width"
